### ISSUE TITLE
What's your favorite project on GitHub and why?

### ISSUE THREAD

**Issue by sindresorhus** [Haroenv/ama#1]

**Comment by Haroenv** [comment]
My favourite project is the one that sparked my interest for Open Source and community work on GitHub, [lineairealgebra](https://github.com/NorfairKing/lineairealgebra) by @NorfairKing. When studying physics Linear Algebra was one of the most complicated courses, and Syd created a whole book together with students from different years concerning answers to the questions in the teacher's literature. 

He decided not to share the book as pdf, but rather share the source code, to make people read everything and make the barrier to contributing lower. 

That was my first pull request and the reason I made a GitHub account.

**Comment by NorfairKing** [comment]
#proud
