### ISSUE TITLE
Where do you live?

### ISSUE THREAD

**Issue by SamVerschueren** [Haroenv/ama#4]
In Bruges of course... Be as specific as you want (area, street, postal code ...)

**Comment by Haroenv** [comment]
Currently live near to the center of Bruges, by the Komvest and study in Gent, but I don't have a dorm there.

**Comment by SamVerschueren** [comment]
Cool, my doctor is located in that area :).

**Comment by Haroenv** [comment]
Interesting, now I just have to find a way to make you sick :p

**Comment by SamVerschueren** [comment]
Scary! Are you going to stalk me :|?
