### ISSUE TITLE
How do you teach yourself complex Software frameworks?

### ISSUE THREAD

**Issue by arjunmayilvaganan** [Haroenv/ama#5]
Little background here: I feel like my university syllabus is a little out of dated and I've been teaching myself a lot of stuff.

I'm feeling Self teaching of certain Software frameworks to be really difficult and frustrating, though I never feel like stopping, but I'm not really consistent. I'm assuming that you are a Self taught programmer, being a student yourself.

Do you have any tips for me?

**Comment by Haroenv** [comment]
I usually find small projects or joke projects and then follow simple intros and googling. If it's too much work or I'm not feeling satisfied, then I'm probably going to stop doing it, there's more than enough time in your life you're going to be forced to do things you don't really like, so things you do in your free time should be fun. 

Thanks for this question, it's quite novel!

**Comment by arjunmayilvaganan** [comment]
> ...there's more than enough time in your life you're going to be forced to do things you don't really like, so things you do in your free time should be fun.

I can't disagree with that.

The actual fun lies in building stuff. But, trying to get ourself familiar with the tool that could help us build the stuff might not be very fun.

Also, there is this quote that I'd like to share at this moment. I don't remember the exact words, but it goes like this:

> Passion may not be something that you might always have fun doing. But, it's something that you'd still want to keep doing what so ever.
